### ISSUE TITLE
During composer update error

### ISSUE THREAD

**Issue by ghost** [jeremykenedy/laravel-admin#1]
Problem 1
    - intervention/image 2.3.5 requires ext-fileinfo \* -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.3.4 requires ext-fileinfo \* -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.3.3 requires ext-fileinfo \* -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.3.2 requires ext-fileinfo \* -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.3.1 requires ext-fileinfo \* -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.3.0 requires ext-fileinfo \* -> the requested PHP extension fileinfo is missing from your system.
    - Installation request for intervention/image ^2.3 -> satisfiable by intervention/image[2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5].

**Comment by jeremykenedy** [comment]
That is your local/dev systems PHP being out of date.

**Comment by ghost** [comment]
But I'm using PHP version 5.5.6

**Comment by jeremykenedy** [comment]
http://stackoverflow.com/questions/24850136/i-have-ext-fileinfo-but-composer-says-it-is-missing

**Comment by ghost** [comment]
thnx
