### ISSUE TITLE
 Undefined variable: access

### ISSUE THREAD

**Issue by ghost** [jeremykenedy/laravel-admin#2]
there is some error after verify the email 
ErrorException in UserController.php line 36:
Undefined variable: access

**Comment by jeremykenedy** [comment]
Need to seed

**Comment by ghost** [comment]
another issue

Trying to get property of non-object (View: D:\xampp\htdocs\admin\resources\views\admin\modules\twitter\twitter-user-home-timeline.blade.php) (View: D:\xampp\htdocs\admin\resources\views\admin\modules\twitter\twitter-user-home-timeline.blade.php)

**Comment by jeremykenedy** [comment]
I would suggest setting up a homestead vagrant dev environment, all your reported issues are not actual issues with the code but issues with your environment.
