### ISSUE TITLE
server goes down when routing to dashboard

### ISSUE THREAD

**Issue by DigitalCoder** [jeremykenedy/laravel-admin#4]
Hi,

after processing all the installation
then register a user and log on

the page is redirected to dashboard page and show this message : 

> Web page unavailable
> 
> ERR_CONNECTION_REFUSED
> 
> Google Chrome to connect to localhost attempt was rejected. It is possible that the Web site is blocked or that your network is not configured properly.

In my terminal my Laravel development server stop to serve

Do you have an idea ?

Thanks for advance !

**Comment by jeremykenedy** [comment]
Hmmmm, what dev environment are you using?

**Comment by jeremykenedy** [comment]
Try creating a homestead instance with the instructions here:
http://laravelcoding.com/blog/laravel-5-beauty-setting-up-an-os-x-or-linux-machine

**Comment by jeremykenedy** [comment]
Also, maybe check this out: http://stackoverflow.com/questions/29410362/local-host-not-working-with-laravel-err-connection-refused-after-first-time-a-p

**Comment by DigitalCoder** [comment]
Mac OSX
Laravel 5.2
Mysql BDD

**Comment by DigitalCoder** [comment]
I've change proxy browser config 
and I still have the error
<img width="602" alt="capture d ecran 2016-02-26 a 10 07 45" src="https://cloud.githubusercontent.com/assets/1869232/13347982/25099d90-dc71-11e5-9908-249ff9308e20.png">

![capture d ecran 2016-02-26 a 09 54 06](https://cloud.githubusercontent.com/assets/1869232/13347580/ff3cadca-dc6e-11e5-9de2-426ee7c7f8aa.png)

**Comment by jeremykenedy** [comment]
I think it's an issue with you dev environment configuration.  Try setting up a homestead vagrant instance.
